POST http://localhost:3003/user/signup
Content-Type: application/json

{
    "name": "Andre Andrade",
    "email": "andre@email.com",
    "password": "123456",
    "role": "ADMIN"
}
###
POST http://localhost:3003/user/login
Content-Type: application/json

{
    "email": "bernardo@email.com",
    "password": "123456"
}
###
GET http://localhost:3003/user/select
Content-Type: application/json
###
PUT http://localhost:3003/user/edit
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjI3OWQ4YzRkLTA2OTMtNGUwMy05OWJkLTcxNDBjZDk5ZTZkZSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY2OTQxMDI0NCwiZXhwIjoxNjY5NDEzODQ0fQ.RdJgig79ZzhGOfDd2x3jh2YxXbjBwYFalxquS3TH7XA
Content-Type: application/json

{
    "name": "Alberto Bernardes",
    "email": "bernardo@email.com",
    "password": "123456",
    "role": "ADMIN"
}
###
POST http://localhost:3003/band/create
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjM0YjlhMmEzLTFmZDItNDc0ZS05Yjc1LTUyY2U5MWQwODA4OSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY2OTQxMTI2NiwiZXhwIjoxNjY5NDE0ODY2fQ.Kzwo8L5E858ENoK3ZgGhymlRX4O5PPTiiP5I1fCyseY
Content-Type: application/json

{
    "name": "Os Maneiros",
    "music_genre": "Rock Paulera",
    "responsible": "Jordana Jordan"
}
###
GET http://localhost:3003/band/find
Content-Type: application/json

{
    "name": "Os Maneiros"
}