POST http://localhost:3003/user/signup
Content-Type: application/json

{
    "name": "Jordana Jordan",
    "email": "jordana@email.com",
    "password": "123456",
    "role": "ADMIN"
}
###
POST http://localhost:3003/user/login
Content-Type: application/json

{
    "email": "jordana@email.com",
    "password": "123456"
}
###
GET http://localhost:3003/user/select
Content-Type: application/json
###
PUT http://localhost:3003/user/edit
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImIwZWE0NDRjLWI0OWItNDE3My1hNGE3LWE3YmVjM2E4ZTQ5MiIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY2OTU5NTQ3OCwiZXhwIjoxNjY5NTk5MDc4fQ.kZRutQgbctbx4K9sdfPeEBHXLjU344vMQdR2wIOfMpk
Content-Type: application/json

{
    "name": "Alberto Bernardes",
    "email": "bernardo@email.com",
    "password": "123456",
    "role": "ADMIN"
}
###
POST http://localhost:3003/band/create
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImIwZWE0NDRjLWI0OWItNDE3My1hNGE3LWE3YmVjM2E4ZTQ5MiIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY2OTU5NTQ3OCwiZXhwIjoxNjY5NTk5MDc4fQ.kZRutQgbctbx4K9sdfPeEBHXLjU344vMQdR2wIOfMpk
Content-Type: application/json

{
    "name": "Os Maneiros",
    "music_genre": "Rock Paulera",
    "responsible": "Jordana Jordan"
}
###
GET http://localhost:3003/band/find
Content-Type: application/json

{
    "name": "Os Maneiros"
}
###
POST http://localhost:3003/show/create
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImIwZWE0NDRjLWI0OWItNDE3My1hNGE3LWE3YmVjM2E4ZTQ5MiIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY2OTU5NTQ3OCwiZXhwIjoxNjY5NTk5MDc4fQ.kZRutQgbctbx4K9sdfPeEBHXLjU344vMQdR2wIOfMpk
Content-Type: application/json

{
    "week_day": "Sexta",
    "start_time": "12",
    "end_time": "13",
    "band_id": "5faa4d58-ff89-4e4c-9fa3-888cc6738ed9"
}
###
GET http://localhost:3003/show/select
Content-Type: application/json

